### ISSUE TITLE
SMB server seems not to work on Raspberry Pi 3 (armv7l)

### ISSUE THREAD

**Issue by maxstrauch** [adobe/node-smb-server#29]
When running the untouched checkout from this git repo on my Mac everything works as expected (node v6.9.3). But when running the same untouched checkout on the Raspberry Pi 3 I can connect to the server, enter a user name and a password (it seems that they are validated) but then a message comes up that there might be no shares or I haven't enough rights to access them. See the log (everything set to `debug`) below. 

By comparing this log to the log of the working instance on my Mac I discovered the following differences:

(1)
`debug: [SMB] [SESSION_SETUP_ANDX] maxBufferSize: 33028, maxMpxCount: 50, vcNumber: 454, sessionKey: 1, capabilities: 10000000000000001100000001011100, accountName: test, primaryDomain: ERIC, nativeOS: Mac OS X 10.10, nativeLanMan: SMBFS 3.0.0`
**vcNumber** is 454 but on the working instance it is 455

(2)
`debug: [SPI] [ipc] tree.open /srvsvc`
`debug: [SPI] [ipc] file.open /srvsvc`
**These two lines are printed on the working copy but not on the Pi**

(3)
`debug: [SMB] [TRANS_TRANSACT_NMPIPE] fid: 1 [fileName: srvsvc], data: 050000031000000054000000000000003c00000000000f00010000000500000000000000050000006500720069006300000000000100000001000000010000000000000000000000ffffffff0100000000000000`
**The `data` value differs and therefore also the variables `totalDataCount` and `dataCount` in the line before**

Log from the Pi:
```
# uname -a
Linux eric 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
# node -v
v6.10.2
# node index.js 
info: [SRV] logging initialized.
info: [SRV] configuration successfully read: 
debug: [SRV] registering share syncfilestart event
debug: [SRV] registering share syncfileend event
debug: [SRV] registering share syncfileerr event
debug: [SRV] registering share syncfileabort event
debug: [SRV] registering share syncfileprogress event
debug: [SRV] registering share syncerr event
debug: [SRV] registering share syncpurged event
debug: [SRV] registering share syncconflict event
debug: [SRV] registering share folderlist event
debug: [SRV] registering share requestqueueinit event
info: [SRV] [3546] SMB server started listening on port 8445
info: [SRV] established client connection #1 from [192.168.0.2:61246] -> [192.168.0.9:8445]
debug: [SMB] [NEGOTIATE] dialects: NT LM 0.12,SMB 2.002,SMB 2.???
debug: [SMB] [SESSION_SETUP_ANDX] maxBufferSize: 33028, maxMpxCount: 50, vcNumber: 454, sessionKey: 1, capabilities: 10000000000000001100000001011100, accountName: test, primaryDomain: ERIC, nativeOS: Mac OS X 10.10, nativeLanMan: SMBFS 3.0.0
debug: [SMB] [TREE_CONNECT_ANDX] flags: 1000, password: 00, service: ?????, path: \\eric\IPC$
debug: [SMB] [NT_CREATE_ANDX] flags: 10000, rootDirectoryFID: 0, desiredAccess: 11000000000000000000000000000000, allocationSize: 0, extFileAttributes: 10000000, shareAccess: 11, createDisposition: 0x1, createOptions: 0, impersonationLevel: 0x2, securityFlags: 0, fileName: \srvsvc
debug: [SMB] [TRANSACTION][TRANS_TRANSACT_NMPIPE] totalParameterCount: 0, parameterCount: 0, totalDataCount: 72, dataCount: 72, flags: 0
debug: [SMB] [TRANS_TRANSACT_NMPIPE] fid: 1 [fileName: srvsvc], data: 05000b0310000000480000000100000000800080000000000100000000000100c84f324b7016d30112785a47bf6ee18803000000045d888aeb1cc9119fe808002b10486002000000
debug: [DCERPC] bound to SRVSVC v3.0 (4b324fc8-1670-01d3-1278-5a47bf6ee188)
debug: [SMB] [TRANSACTION][TRANS_TRANSACT_NMPIPE] totalParameterCount: 0, parameterCount: 0, totalDataCount: 84, dataCount: 84, flags: 0
debug: [SMB] [TRANS_TRANSACT_NMPIPE] fid: 1 [fileName: srvsvc], data: 050000031000000054000000000000003c00000000000f00010000000500000000000000050000006500720069006300000000000100000001000000010000000000000000000000ffffffff0100000000000000
debug: [DCERPC] NetShareEnumAll (SRVSVC v3.0)
debug: [SMB] [CLOSE] fid: 1 [fileName: srvsvc], lastModified: 4294967295
debug: [SMB] [TREE_DISCONNECT] tid: 1
debug: [SMB] [LOGOFF_ANDX] uid: 1
info: [SRV] client #1 disconnected (received: 1kb, sent: 1kb)
```

**Comment by stefan-guggisberg** [comment]
how do you connect? do you connect to a specific share (e.g. <raspberry>:8445/fs) ?

**Comment by maxstrauch** [comment]
I used Finder on Mac OS X 10.12 (in both cases) using "Connect to server" with address `smb://eric:8445`

**Comment by stefan-guggisberg** [comment]
when you connect to the root of the SMB server the available shares
will be enumerated. this is a different protocol (DCE/RPC) which seems
to cause problems on raspberry.

please try connecting to smb://eric:8445/fs

does that work?

**Comment by maxstrauch** [comment]
Works without a problem.

**Comment by stefan-guggisberg** [comment]
thanks for the feedback. i'll investigate the issue of enumerating shares
on the raspberry when i find some time but don't hold your breath.

**Comment by stefan-guggisberg** [comment]
didn't get to investigate the enumerating shares issue on raspberry due to lack of bandwidth. if this an important feature for you please feel free to open a new specific issue. 

apart from enumerating shares `node-smb-server` apparently works for you, therefore closing this issue.
