### ISSUE TITLE
windows client cannot connect

### ISSUE THREAD

**Issue by sunnipaul** [adobe/node-smb-server#43]
I am using windows 10 to connect to the server.
It failed with error message on the server side:

error: [SMB] unhandled exception while handling request TypeError: Cannot read property 'negotiateMsg' of undefined
    at handle (/mnt/sdb/dev/web/opensource/node-smb-server/lib/smb/cmd/session_setup_andx.js:142:15)

**Comment by stefan-guggisberg** [comment]
thanks for reporting this issue. it seems like there's a problem with the initial handshake (sessionKey
passed in SMB_COM_SESSION_SETUP_ANDX msg seems to not correspond to the sessionKey returned by the SMB_COM_NEGOTIATE msg. 

if you can provide a wireshark packet dump of the failed handshake i'll investigate further.

**Comment by Panicsystem** [comment]
Make sure your Windows 10 registry has the value LmCompatibilityLevel set to 0
https://technet.microsoft.com/fr-fr/library/cc960646.aspx

**Comment by wendel841** [comment]
Hi all, +1 for this issue. Linux mint 17.3, is it's possible to make it work without fixing registry or something else because there is no possibility to make this change for all clients?

**Comment by diedusta** [comment]
Christopher Hertel, Implementing CIFS, Appendix D
http://ubiqx.org/cifs/Book.html

 ULONG SessionKey; Session key (valid iff VcNumber != 0)

**Comment by sazarkin** [comment]
Hi! I this issue active? I can provide packet dump with failed negotiation.

**Comment by stefan-guggisberg** [comment]
yes, this issue is active. i just haven't found the time to setup an environment and dig into. a packet dump (*.cap,*.pcap) would be great.

**Comment by sazarkin** [comment]
this is linux client
[cifs-neg-fail.pcap.zip](https://github.com/adobe/node-smb-server/files/1828758/cifs-neg-fail.pcap.zip)

**Comment by sazarkin** [comment]
this is windows
[cifs-neg-fail-win.pcap.zip](https://github.com/adobe/node-smb-server/files/1828786/cifs-neg-fail-win.pcap.zip)

**Comment by stefan-guggisberg** [comment]
thanks! i'll look into it when i find some time. it might take a while, so don't hold your breath.

**Comment by stefan-guggisberg** [comment]
i've fixed a couple of issues and i am now able to connect from windows 10. 

in order to test it, make sure you set `domainName` in `config.json` (e.g. to `"WORKGROUP"`) and set `extendedSecurity` to `false`. 

there's still a problem with the extended security handshake with windows clients.

**Comment by stefan-guggisberg** [comment]
got extended security working with windows client.

it's now possible to connect from windows 10 client.

make sure you set `domainName` in `config.json` (e.g. to `"WORKGROUP"`.)

**Comment by stefan-guggisberg** [comment]
closing issue for now.
