### ISSUE TITLE
Invalid NTLMSSP message signature, Ubuntu 16.04 LTS x64

### ISSUE THREAD

**Issue by mStirner** [adobe/node-smb-server#63]
[server.log](https://github.com/adobe/node-smb-server/files/2371588/server.log)
[smb.log](https://github.com/adobe/node-smb-server/files/2371589/smb.log)

> info: [SRV] logging initialized.
> info: [SRV] configuration successfully read: /home/marc/Downloads/node-smb-server-master/config.json
> info: [SRV] [15117] SMB server started listening on port 8445
> info: [SRV] established client connection #1 from [127.0.0.1:53272] -> [127.0.0.1:8445]
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> info: [SRV] client #1 disconnected (received: 0kb, sent: 0kb)
> info: [SRV] established client connection #2 from [127.0.0.1:53274] -> [127.0.0.1:8445]
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> info: [SRV] client #2 disconnected (received: 0kb, sent: 0kb)
> info: [SRV] established client connection #3 from [127.0.0.1:53276] -> [127.0.0.1:8445]
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> info: [SRV] client #3 disconnected (received: 0kb, sent: 0kb)
> info: [SRV] established client connection #4 from [127.0.0.1:53278] -> [127.0.0.1:8445]
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> info: [SRV] client #4 disconnected (received: 0kb, sent: 0kb)
> info: [SRV] established client connection #5 from [127.0.0.1:53280] -> [127.0.0.1:8445]
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> info: [SRV] client #5 disconnected (received: 0kb, sent: 0kb)
> info: [SRV] established client connection #6 from [127.0.0.1:53282] -> [127.0.0.1:8445]
> warn: [SRV] invalid NTLMSSP message signature: data: 0x604806062b060105
> info: [SRV] client #6 disconnected (received: 0kb, sent: 0kb)

OS: Ubuntu 16.04 LTS x64
Node: v9.11.2

**Comment by stefan-guggisberg** [comment]
thanks for posting this issue.

please provide more information:

* node-smb-server version
* client information (os, version)
* your config.json

**Comment by mStirner** [comment]
node-smb-version = github master branch
client: Windows 7 + Windows PE 10 + CloneZilla (debian)
config.json default

**Comment by stefan-guggisberg** [comment]
i don't have Windows 7 and i don't know what Windows PE 10 is.

i've successfully tested connecting from both Windows 8 Enterprise and Windows 10 Enterprise clients using the default `config.json` (apart from changing the port to 445).

Please set`extendedSecurity` to `false` in `config.js` and try again.

**Comment by stefan-guggisberg** [comment]
by the way: in your log i see that your smb server listens on `8445`. AFAIK windows only supports port `445`. please change port in `config.json` to `445` and restart server with `sudo`.

**Comment by stefan-guggisberg** [comment]
@mStirner did you have a chance to try again with above suggestions?

**Comment by stefan-guggisberg** [comment]
no feedback, closing
