### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by 8wWDCfjjbq** [adobe/node-smb-server#66]
Followed instructions from the readme, started the server properly.
Entered `\\192.168.1.5:8445` in the File Explorer omnibox. Got error
```
Windows can't find "\\192.168.1.5:8445"
```

In the Node.js console observed error message

```
info: [SRV] established client connection #1 from [192.168.1.5:64931] -> [192.168.1.5:8445]
error: [SMB] unsupported NetBIOS session service message type: 79
```

**Comment by stefan-guggisberg** [comment]
i see that you  run `node-smb-server` on port `8445`. AFAIK the windows SMB client only supports port `445`. if you run both server and the client on windows you have to use port `445`. you'll have to stop the windows built-in SMB server and start `node-smb-server` on port `445` (requires Administrator privileges).

**Comment by 8wWDCfjjbq** [comment]
@stefan-guggisberg

Articles we found say that Windows Explorer supports any SMB port of the localhost. Tested using Python SMB implementation and works on any port.

Also tried disabling port 445, but faced difficulties. Disabled SMB1 and SMB2 windows server from command line, registry editor and control panel, restarted the PC, but the port 445 is still used. It is used by the `System` process with PID 4, so it cannot be killed. Searched on the Internet and found that other people also have troubles disabling port 445 on Windows 8.1, since it probably isn't used by SMB server, but by the system itself.

According to the fact that the issue is not resolved, is there any chance it can be reopened and reconsidered for further investigation?

**Comment by stefan-guggisberg** [comment]
@8wWDCfjjbq could you please add the links to the mentioned articles? to the best of my knowledge (and personal experience) it's not possible to directly connect from a windows client to an smb server running on a non-standard port. i'm happy to be proven wrong.

**Comment by 8wWDCfjjbq** [comment]
Did more investigation. The limitation of the port range to 445 is related to the Windows File Explorer (stand-alone Windows program), rather to the Windows itself. Custom file explorer implementations allow all ports. Disabling native port 445 on Windows 8.1 seems to be impossible (see [this](https://social.technet.microsoft.com/Forums/systemcenter/en-US/571856eb-d275-4f8d-b90c-a4b3db60c22f/i-cant-connect-fileserver-smb-through-port-445?forum=winserverfiles)), making this module useless on that platform.

The error that was appearing (`error: [SMB] unsupported NetBIOS session service message type: 79`) should at least be more useful. The byte 79 (`'\x4f'`) is part of the `OPTIONS / HTTP/1.1` header that File Explorer tries to send. It took our team a decent amount of time to figure that out.

Thanks for your time. This seems to be a file explorer limitation, rather than the node-smb issue.

**Comment by stefan-guggisberg** [comment]
thanks for the update!

**Comment by a8767c36** [comment]
I just figured out that it is possible to disable the built-in Windows process listening on port 445:
Open Services.msc -> Scroll down to the "Server" service -> disable it. Reboot.
Then you can run the node-smb-server on your local windows machine.

**Comment by stefan-guggisberg** [comment]
Thanks for the hint! Feel free to create a pull request to update the README.
