### ISSUE TITLE
android smb client occurs errors

### ISSUE THREAD

**Issue by misogihagi** [adobe/node-smb-server#71]
Hello

node-smb-server works with windows smb client. I tried.
but I tried a few apps on android, it occurs errors below

```
 node ./index.js

info: [SRV] logging initialized.
info: [SRV] configuration successfully read: /data/data/com.termux/files/home/node-smb-server/config.json
(node:9826) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info: [SRV] [9826] SMB server started listening on port 445
info: [SRV] established client connection #1 from [192.168.0.100:58224] -> [192.168.0.103:445]
error: [SMB] encountered unhandled exception at the handler level. exiting message=The value of "offset" is out of range. It must be >= 0 and <= 72. Received 76, stack=RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 72. Received 76
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readUInt32LE (internal/buffer.js:211:5)
    at netShareEnumAll (/data/data/com.termux/files/home/node-smb-server/lib/dcerpc/pdu/request.js:200:29)
    at handle (/data/data/com.termux/files/home/node-smb-server/lib/dcerpc/pdu/request.js:70:7)
    at handle (/data/data/com.termux/files/home/node-smb-server/lib/smb/cmd/trans/trans_transact_nmpipe.js:137:5)
    at handle (/data/data/com.termux/files/home/node-smb-server/lib/smb/cmd/transaction.js:129:5)
    at Domain.<anonymous> (/data/data/com.termux/files/home/node-smb-server/lib/smb/handler.js:94:11)
    at Domain.run (domain.js:373:14)
    at /data/data/com.termux/files/home/node-smb-server/lib/smb/handler.js:92:11
    at /data/data/com.termux/files/home/node-smb-server/node_modules/async/lib/async.js:181:20, code=ERR_OUT_OF_RANGE, removeListener=function updateExceptionCapture() {
  if (stack.every((domain) => domain.listenerCount('error') === 0)) {
    setUncaughtExceptionCaptureCallback(null);
  } else {
    setUncaughtExceptionCaptureCallback(null);
    setUncaughtExceptionCaptureCallback((er) => {
      return process.domain._errorHandler(er);
    });
  }
}, newListener=function updateExceptionCapture() {
  if (stack.every((domain) => domain.listenerCount('error') === 0)) {
    setUncaughtExceptionCaptureCallback(null);
  } else {
    setUncaughtExceptionCaptureCallback(null);
    setUncaughtExceptionCaptureCallback((er) => {
      return process.domain._errorHandler(er);
    });
  }
}, error=function (err) {
          logger.error('encountered unhandled exception at the handler level. exiting', err);
          process.exit(1);
        }, _eventsCount=3, _maxListeners=undefined, members=[], domainThrown=true
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-smb-server@0.10.37 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-smb-server@0.10.37 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by stefan-guggisberg** [comment]
When you connect to the root of the SMB server the available shares
will be enumerated. This is a different protocol (DCE/RPC) which seems
to cause problems on Android. See #29 for a related problem.

Please try connecting to a specific share, e.g. `smb://<host>:<port>/fs` instead of `smb://<host>:<port>`

Does that work?

**Comment by misogihagi** [comment]
The result was same.


-`info: [SRV] logging initialized.
info: [SRV] configuration successfully read: /data/data/com.termux/files/home/node-smb-server/config.json
(node:9826) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info: [SRV] [9826] SMB server started listening on port 445
info: [SRV] established client connection #1 from [192.168.0.100:58224] -> [192.168.0.103:445]
error: [SMB] encountered unhandled exception at the handler level. exiting message=The value of "offset" is out of range. It must be >= 0 and <= 72. Received 76, stack=RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 72. Received 76
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readUInt32LE (internal/buffer.js:211:5)
    at netShareEnumAll (/data/data/com.termux/files/home/node-smb-server/lib/dcerpc/pdu/request.js:200:29)
    at handle (/data/data/com.termux/files/home/node-smb-server/lib/dcerpc/pdu/request.js:70:7)
    at handle (/data/data/com.termux/files/home/node-smb-server/lib/smb/cmd/trans/trans_transact_nmpipe.js:137:5)
    at handle (/data/data/com.termux/files/home/node-smb-server/lib/smb/cmd/transaction.js:129:5)
    at Domain.<anonymous> (/data/data/com.termux/files/home/node-smb-server/lib/smb/handler.js:94:11)
    at Domain.run (domain.js:373:14)
    at /data/data/com.termux/files/home/node-smb-server/lib/smb/handler.js:92:11
    at /data/data/com.termux/files/home/node-smb-server/node_modules/async/lib/async.js:181:20, code=ERR_OUT_OF_RANGE, removeListener=function updateExceptionCapture() {
  if (stack.every((domain) => domain.listenerCount('error') === 0)) {
    setUncaughtExceptionCaptureCallback(null);
  } else {
    setUncaughtExceptionCaptureCallback(null);
    setUncaughtExceptionCaptureCallback((er) => {
      return process.domain._errorHandler(er);
    });
  }
}, newListener=function updateExceptionCapture() {
  if (stack.every((domain) => domain.listenerCount('error') === 0)) {
    setUncaughtExceptionCaptureCallback(null);
  } else {
    setUncaughtExceptionCaptureCallback(null);
    setUncaughtExceptionCaptureCallback((er) => {
      return process.domain._errorHandler(er);
    });
  }
}, error=function (err) {
          logger.error('encountered unhandled exception at the handler level. exiting', err);
          process.exit(1);
        }, _eventsCount=3, _maxListeners=undefined, members=[], domainThrown=true
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-smb-server@0.10.37 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-smb-server@0.10.37 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by stefan-guggisberg** [comment]
Hmm, weird. Seems like the Android client still tries to enumerate the SMB shares.

I don't have an Android phone neither do I have the time to debug the issue, sorry. `node-smb-server` is primarily targeted to macOS clients. Other clients might work (your mileage may vary though) but are not officially supported. Sorry. 

If you wish to debug the issue yourself  you'll need to capture and analyse the SMB protocol exchange between your Android client and `node-smb-server` using Wireshark (or similar). Pull requests are welcome!

**Comment by misogihagi** [comment]
hello
here is my present. when debugging node-smb-server, I feel it is better to test from network packets like pcap.
There is also the android's pcap.  Finally, I could not find the reason why the error occurred.
But I hope this commit help your debugging.
P.S.
I wondered if commit on “spec” folder or not.
Should I have put it there?


[android.zip](https://github.com/adobe/node-smb-server/files/5045674/android.zip)

**Comment by stefan-guggisberg** [comment]
Thanks for the pcap file. I found the problem: your client library (apparently jCIFS) used an ancient protocol (`NetShareEnum ` command of the [Lan Manager RAP Protocol](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rap/)) for enumerating SMB shares. This protocol is not used by the macOS client and was therefore not implemented.

FWIW: [NetShareEnum protocol/command details](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rap/48dd86d2-4092-49a4-9024-308f0ed77520)   

I added a fix to gracefully handle this unsupported protocol request: e0e9c03

**Comment by misogihagi** [comment]
Thanks for fixing!
but another problem occured as below
`info: [SRV] logging initialized.
info: [SRV] configuration successfully read: E:\git\node-smb-server\config.json
info: [SRV] [22364] SMB server started listening on port 8445
info: [SRV] established client connection #1 from [192.168.0.100:51364] -> [192.168.0.101:8445]
error: [SMB] encountered unsupported protocol: Microsoft Remote Administration Protocol (RAP)
error: [SMB] 'TRANSACTION' returned error status STATUS_NOT_IMPLEMENTED (0xc0000002)`

[android.zip](https://github.com/adobe/node-smb-server/files/5080311/android.zip)

**Comment by stefan-guggisberg** [comment]
It's the same problem. It's just handled with a proper error message instead of crashing. 

The problem is that the Android client is using an ancient protocol ([Lan Manager RAP Protocol](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rap/fb8d5bd1-e57c-4be1-b063-ec31330bdd58)). This protocol is not used by the macOS client and was therefore never implemented.

Unfortunately I don't have the bandwidth to research and implement it. Neither do I have an Android client. Sorry.
