### ISSUE TITLE
error upon connection: encountered unhandled exception at the handler level. exiting message=The value of "offset" is out of range

### ISSUE THREAD

**Issue by brzssh** [adobe/node-smb-server#72]
hi, the server crashed upon smb connection 

 npm start

> node-smb-server@0.10.36 start /root/node_modules/node-smb-server
> node ./index.js

info: [SRV] logging initialized.
info: [SRV] configuration successfully read: /root/node_modules/node-smb-server/config.json
info: [SRV] [9407] SMB server started listening on port 445
info: [SRV] established client connection #1 from [10.162.130.12:58130] -> [10.162.140.139:445]
**error: [SMB] encountered unhandled exception at the handler level. exiting message=The value of "offset" is out of range. It must be >= 0 and <= 72. Received 73, stack=RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 72. Received 73**
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readUInt16LE (internal/buffer.js:234:5)
    at Object.extractUnicodeBytes (/root/node_modules/node-smb-server/lib/utils.js:190:14)
    at handle (/root/node_modules/node-smb-server/lib/smb/cmd/session_setup_andx.js:83:19)
    at Domain.<anonymous> (/root/node_modules/node-smb-server/lib/smb/handler.js:94:11)
    at Domain.run (domain.js:370:14)
    at /root/node_modules/node-smb-server/lib/smb/handler.js:92:11
    at /root/node_modules/node-smb-server/node_modules/async/lib/async.js:181:20
    at iterate (/root/node_modules/node-smb-server/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/root/node_modules/node-smb-server/node_modules/async/lib/async.js:281:9), code=ERR_OUT_OF_RANGE, removeListener=function updateExceptionCapture() {
  if (stack.every((domain) => domain.listenerCount('error') === 0)) {
    setUncaughtExceptionCaptureCallback(null);
  } else {
    setUncaughtExceptionCaptureCallback(null);
    setUncaughtExceptionCaptureCallback((er) => {
      return process.domain._errorHandler(er);
    });
  }
}, newListener=function updateExceptionCapture() {
  if (stack.every((domain) => domain.listenerCount('error') === 0)) {
    setUncaughtExceptionCaptureCallback(null);
  } else {
    setUncaughtExceptionCaptureCallback(null);
    setUncaughtExceptionCaptureCallback((er) => {
      return process.domain._errorHandler(er);
    });
  }
}, error=function (err) {
          logger.error('encountered unhandled exception at the handler level. exiting', err);
          process.exit(1);
        }, _eventsCount=3, _maxListeners=undefined, members=[], domainThrown=true
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-smb-server@0.10.36 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-smb-server@0.10.36 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-30T08_02_24_508Z-debug.log

**Comment by stefan-guggisberg** [comment]
What SMB Client are you using?

**Comment by brzssh** [comment]
> What SMB Client are you using?

Nmap scanning towards the server.

**Comment by stefan-guggisberg** [comment]
Seems like the scanner intentionally sent a corrupt smb command packet.
