### ISSUE TITLE
Question: Is this comparable to fuse?

### ISSUE THREAD

**Issue by 3cooper** [adobe/node-smb-server#73]
I have a project where I'd like to mount a virtual filesystem based on a directory structure from a website.  On Windows, I have used dokan to accomplish this.  On Mac, I was looking at osxfuse.  Would this project be similar solution to osxfuse?  I have zero experience with smb.  From looking around this seems to be familiar.  I have also looked at Kernelless Filesystem (KFS), but I read somewhere that it doesn't support simultaneous IO and can be slow.  Any information would be greatly appreciated.

**Comment by stefan-guggisberg** [comment]
Hi,

Take a look here: https://github.com/adobe/node-smb-server#developing-a-custom-backend

https://github.com/adobe/node-smb-server/tree/master/lib/spi contains the SPI that you can implement.

https://github.com/adobe/node-smb-server/tree/master/lib/backends/fs is an SPI implementation exposing the local file system.

https://github.com/adobe/node-smb-server/tree/master/lib/backends/jcr OTOH is an implementation exposing a remote JCR (Java Content Repository).

You'll get the idea.
